// This file is automatically @generated by Asphalt.
// It is not intended for manual editing.
declare const assets: {
	add: string
	caretDown: string
	checkmark: string
	extension: string
	icons: {
		toolbarIcon: string
	}
	search: string
}

export = assets