name: CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: CompeyDev/setup-rokit@v0.1.2

      - name: Building plugin
        working-directory: ./plugin
        run: | 
          npm install

          npm run prepare

      - name: Building standalone package
        working-directory: ./runtime
        run: rojo build -o compo.rbxm pack.project.json

      - name: Publish to Wally
        working-directory: ./runtime
        env: 
          WALLY_TOKEN: ${{ secrets.WALLY_AUTH_TOKEN }}
        run: |
          wally publish

      - name: Releasing 
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_PAT }}
          files: |
            ./plugin/compoInspector.rbxm
            ./runtime/compo.rbxm
