name: CI

on:
  push:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: CompeyDev/setup-rokit@v0.1.2

      - name: Building plugin
        working-directory: ./plugin
        run: | 
          npm install
          npm run build

